export enum WorldEvent {
    //PLAYER_CLIENT_SPAWNED = "PLAYER_CLIENT_SPAWNED",
    PLAYER_CLIENT_DESTROYED = "PLAYER_CLIENT_DESTROYED",
    PLAYER_STATE_CHANGED = "PLAYER_STATE_CHANGED",
    TILE_ITEM_STOVE_START_COOK = "TILE_ITEM_STOVE_START_COOK",
    TILE_ITEM_CHANGED = "TILE_ITEM_CHANGED",

    TILE_ITEM_POINTER_DOWN = "TILE_ITEM_POINTER_DOWN",
    TILE_ITEM_POINTER_UP = "TILE_ITEM_POINTER_UP",
    TILE_ITEM_POINTER_OVER = "TILE_ITEM_POINTER_OVER",
    TILE_ITEM_POINTER_OUT = "TILE_ITEM_POINTER_OUT",
}