export enum WorldEvent {
    //PLAYER_CLIENT_SPAWNED = "PLAYER_CLIENT_SPAWNED",
    PLAYER_CLIENT_DESTROYED = "PLAYER_CLIENT_DESTROYED",
    PLAYER_STATE_CHANGED = "PLAYER_STATE_CHANGED",
    TILE_ITEM_STOVE_START_COOK = "TILE_ITEM_STOVE_START_COOK",
    TILE_ITEM_CHANGED = "TILE_ITEM_CHANGED",
}